spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081